import json

students = [
    {
        "id": 11,
        "name": "SANKAMES VS",
        "registerNo": "24VL036",
        "rollno": "24VL036",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "nsankames@gmail.com",
        "achievementTitle": "Project: Digital Clock Simulation",
        "achievement": "Designed and developed a simple digital clock system displaying hours, minutes, and seconds accurately.",
        "projectsOverview": "Digital Clock Simulation",
        "description": "",
        "image": "sankames-vs.jpg",
        "photoUrl": "sankames-vs.jpg",
        "linkedin": "https://www.linkedin.com/in/sankames-sankames-4b2116339",
        "github": ""
    },
    {
        "id": 12,
        "name": "V T RAGHUL VASUN",
        "registerNo": "24VL029",
        "rollno": "24VL029",
        "universityNo": "714024169029",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "vtraghulvasun@gmail.com",
        "achievementTitle": "Internships, Training & Technical Programs",
        "achievement": "Internships: Chip Crafts, Career Ladder, ENTHU, Manfree, SM MOJO TECH.\nWorkshops: FPGA Altera Workshop, Synopsys EDA Tools, Cadence EDA Tools.",
        "projectsOverview": "8-bit ALU, Booth Multiplier, TCAM",
        "description": "",
        "image": "v-t-raghul-vasun.jpg",
        "photoUrl": "v-t-raghul-vasun.jpg",
        "linkedin": "https://www.linkedin.com/in/raghul-vasun-vt-3a804941a",
        "github": ""
    },
    {
        "id": 13,
        "name": "Kavya M",
        "registerNo": "24VL016",
        "rollno": "24VL016",
        "universityNo": "714024169016",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "kavyamanoharan2006@gmail.com",
        "achievementTitle": "Hackathons, Workshops & Technical Events",
        "achievement": "Participated in ROBOCHIPX 24-Hours Hackathon. Attended RISC-V Hands-on Training at IIT Madras. Completed Custom IC Design Mastery using Cadence EDA Tools.",
        "projectsOverview": "",
        "description": "",
        "image": "kavya-m.jpg",
        "photoUrl": "kavya-m.jpg",
        "linkedin": "https://www.linkedin.com/in/kavya-m-9376a2322",
        "github": ""
    },
    {
        "id": 14,
        "name": "Subhashini N",
        "registerNo": "24VL043",
        "rollno": "24VL043",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "subhashininallasamy@gmail.com",
        "achievementTitle": "Workshops & Internships",
        "achievement": "Workshops: PCB Design, VLSI TEST Workshop, VLSI Design Flow from RTL to GDS, Code to chip. Internships: Chip Crafts, Career Ladder, EnthuTech.",
        "projectsOverview": "RTL-to-GDSII Implementation of a Low-Power Edge-AI Safety Monitoring SoC, Edge-AI SoC for ADAS",
        "description": "",
        "image": "subhashini-n.jpg",
        "photoUrl": "subhashini-n.jpg",
        "linkedin": "https://www.linkedin.com/in/subhashini-nallasamy-4ab745328",
        "github": ""
    },
    {
        "id": 15,
        "name": "Varsha V R",
        "registerNo": "24VL052",
        "rollno": "24VL052",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "varshavr24vl@srishakthi.ac.in",
        "achievementTitle": "Internships, Workshops & Hackathons",
        "achievement": "Internships: SM AI MOJO TECH, Manfree Technology, Enthu EdTech, Career Ladder, Chip Crafts. Workshops: Code to Chip, Digital Hardware Design. Hackathons: RoboChipX.",
        "projectsOverview": "Adaptive Dynamic-Precision Sparse Neural Network Accelerator, AMBA AXI4-Lite Master/Slave, SPI Protocol Controller",
        "description": "",
        "image": "varsha-v-r.jpg",
        "photoUrl": "varsha-v-r.jpg",
        "linkedin": "https://www.linkedin.com/in/varsha-ramesh-58840a338",
        "github": ""
    },
    {
        "id": 16,
        "name": "Winston Churchil",
        "registerNo": "24VL053",
        "rollno": "24VL053",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "churchilerd@gmail.com",
        "achievementTitle": "Projects & Development",
        "achievement": "Developing 3d Portfolio websites and AI career roadmap generator web application.",
        "projectsOverview": "3d Portfolio websites and AI career roadmap generator web application",
        "description": "",
        "image": "winston-churchil.jpg",
        "photoUrl": "winston-churchil.jpg",
        "linkedin": "https://www.linkedin.com/in/winstonchurchil21",
        "github": ""
    },
    {
        "id": 17,
        "name": "K.R.Nitin",
        "registerNo": "24VL025",
        "rollno": "24VL025",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "nithunithu2720@gmail.com",
        "achievementTitle": "Internships & Workshops",
        "achievement": "Completed various internships and workshops related to VLSI design.",
        "projectsOverview": "RTL-to-GDSII Design and Physical Implementation of a 16-bit Multiply-Accumulate Unit Using Synopsys",
        "description": "",
        "image": "k-r-nitin.jpg",
        "photoUrl": "k-r-nitin.jpg",
        "linkedin": "https://www.linkedin.com/in/nitin-nitin-63640b",
        "github": ""
    },
    {
        "id": 18,
        "name": "Sakthishree D",
        "registerNo": "24VL033",
        "rollno": "24VL033",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "sakthishree610@gmail.com",
        "achievementTitle": "Rank Holder & Certifications",
        "achievement": "Rank Holder in multiple semesters. Internships at Chip Crafts, Manfree, Career Ladder, Enthu Technologies, SM AI MOJO Tech. Certifications in VLSI, RISC-V, Verilog HDL.",
        "projectsOverview": "32 bit RISC V BASED ADAPTIVE PRECISION ACCELERATOR, Multi-GPU Architecture, BIST Controller",
        "description": "",
        "image": "sakthishree-d.jpg",
        "photoUrl": "sakthishree-d.jpg",
        "linkedin": "https://www.linkedin.com/in/sakthishree-d-746115339",
        "github": ""
    },
    {
        "id": 19,
        "name": "Kiruthika S",
        "registerNo": "24VL017",
        "rollno": "24VL017",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "kiruthika.shanmugam006@gmail.com",
        "achievementTitle": "Workshops & Internships",
        "achievement": "10-Day Cadence VLSI Design Workshop, 2-Day IoT Workshop, 2-Day FPGA Workshop. Multiple internships from Career Ladder, Enthu Tech, Embuzz, Chip Crafts, Manfree, Maven Silicon.",
        "projectsOverview": "Fault Controller for Medical Devices, Booth Multiplier, SPI, BIST, UART, AXI4-Lite, MAC Unit, CAN Protocol",
        "description": "",
        "image": "kiruthika-s.jpg",
        "photoUrl": "kiruthika-s.jpg",
        "linkedin": "https://www.linkedin.com/in/kiruthika-shanmugam-5a6092330",
        "github": ""
    },
    {
        "id": 20,
        "name": "Roobashri S",
        "registerNo": "24VL032",
        "rollno": "24VL032",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "roobashrisenthilmurugan@gmail.com",
        "achievementTitle": "Workshops, Internships & Hackathons",
        "achievement": "Workshops: PCB Design, VLSI TEST, VLSI Design Flow, Code to chip. Internships: Chip Crafts, Career Ladder, EnthuTech. Hackathon: Bharat AI-Soc Student Challenge.",
        "projectsOverview": "Reconfigurable Neuromorphic Processor, STM32F446RE PCB Controller Board, Smart 3S BMS",
        "description": "",
        "image": "roobashri-s.jpg",
        "photoUrl": "roobashri-s.jpg",
        "linkedin": "https://www.linkedin.com/in/roobashri-senthilmurugan",
        "github": ""
    },
    {
        "id": 21,
        "name": "Soorya Velaa P",
        "registerNo": "24VL040",
        "rollno": "24VL040",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "suryavela9120@gmail.com",
        "achievementTitle": "Workshops, Training & NCC",
        "achievement": "Workshops: Cadence, IOT, FPGA. Internships: Career Ladder, Enthu tech, Embuzz, Chip Crafts, Manfree. NCC CADET B Certificate holder with A grade.",
        "projectsOverview": "Booth multiplier, PIPELINE, SPI, MFCC Accelerator",
        "description": "",
        "image": "soorya-velaa-p.jpg",
        "photoUrl": "soorya-velaa-p.jpg",
        "linkedin": "https://www.linkedin.com/in/soorya-velaa",
        "github": ""
    },
    {
        "id": 22,
        "name": "SRI VATSAN P",
        "registerNo": "24VL041",
        "rollno": "24VL041",
        "universityNo": "714024169041",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "srivatsan132006@gmail.com",
        "achievementTitle": "Internships, Workshops & Certifications",
        "achievement": "Internships: Embuzz, Chip Craft, Manfree, Enthu Technology. Hackathons: 24-Hour Hackathon – RIT College. Certifications: Synopsys ASIC Design Flow, Digital Hardware & FPGA Implementation.",
        "projectsOverview": "Configurable Dynamic Memory-Aware AXI4-Stream Sparse Matrix Acceleration Engine, DDR SDRAM Controller",
        "description": "",
        "image": "sri-vatsan-p.jpg",
        "photoUrl": "sri-vatsan-p.jpg",
        "linkedin": "https://www.linkedin.com/in/sri-vatsan-84990a338",
        "github": ""
    },
    {
        "id": 23,
        "name": "Pratheep D",
        "registerNo": "24VL026",
        "rollno": "24VL026",
        "universityNo": "714024169026",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "pratheepdcbe@gmail.com",
        "achievementTitle": "Certifications & Training",
        "achievement": "MATLAB Onramp Certification. Participated in Inter-College Cadence Workshop. Training in RISC Processor Architecture and Java.",
        "projectsOverview": "RTL-to-GDSII Implementation of a Sparse Multi-Head Attention Accelerator for Transformer-Based Large Language Model Inference",
        "description": "",
        "image": "pratheep-d.jpg",
        "photoUrl": "pratheep-d.jpg",
        "linkedin": "https://www.linkedin.com/in/pratheep-vlsi",
        "github": ""
    },
    {
        "id": 24,
        "name": "PUGAZHENDHI S",
        "registerNo": "24VL028",
        "rollno": "24VL028",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "spugazhendhi2007@gmail.com",
        "achievementTitle": "Training & Internships",
        "achievement": "Chip Design Using Cadence Tool Chain (RTL to GDSII), Back-End Design of Digital Logic Circuits, VLSI Layout Design Internship.",
        "projectsOverview": "RISC-V Processor with External Memory, PPA Optimization of Hardware Accelerator, Low Power 8-bit ALU",
        "description": "",
        "image": "pugazhendhi-s.jpg",
        "photoUrl": "pugazhendhi-s.jpg",
        "linkedin": "https://www.linkedin.com/in/s-pugazh-pugazhendhi-657907338",
        "github": ""
    },
    {
        "id": 25,
        "name": "Mohammed Ayman M",
        "registerNo": "24VL021",
        "rollno": "24VL021",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "mohammedayman4381@gmail.com",
        "achievementTitle": "Projects, Internships & Hackathons",
        "achievement": "VLSI Internship – SM AI Mojo Tech. SEMICON / Semiconductor Hackathon Participation. Technical Workshops & Hands-on Learning covering VLSI design, FPGA, AI/ML.",
        "projectsOverview": "SEMIRESTORE-AI: AI-Based Restoration of Degraded Images for Semiconductor Inspection",
        "description": "",
        "image": "mohammed-ayman-m.jpg",
        "photoUrl": "mohammed-ayman-m.jpg",
        "linkedin": "https://www.linkedin.com/in/mohammed-ayman-m",
        "github": ""
    },
    {
        "id": 26,
        "name": "S. Thirumurugan",
        "registerNo": "24VL050",
        "rollno": "24VL050",
        "universityNo": "714024169050",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "thirumurugans2945@gmail.com",
        "achievementTitle": "Internships, Training & Workshops",
        "achievement": "Internships: Chip Crafts, Embuzz, Career Ladder, ENTHU, Manfree. Workshops: FPGA Altera, Synopsys EDA, Cadence EDA.",
        "projectsOverview": "RISC-V CPU, Secure VPU, 8-bit ALU, Booth Multiplier, TCAM",
        "description": "",
        "image": "s-thirumurugan.jpg",
        "photoUrl": "s-thirumurugan.jpg",
        "linkedin": "https://linkedin.com/in/thiru-murugan-264111339",
        "github": ""
    },
    {
        "id": 27,
        "name": "SANJEEV GH",
        "registerNo": "24VL034",
        "rollno": "24VL034",
        "universityNo": "",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "sanjeevgh27@gmail.com",
        "achievementTitle": "Internships & Technical Achievements",
        "achievement": "Completed 53+ VLSI projects using Synopsys and Cadence. Developed BatterySense X (91.94% core utilization, zero DRC violations).",
        "projectsOverview": "BatterySense X – Intelligent Battery Sensing & Health Monitoring ASIC, ECG Signal Power-Line Noise Removal",
        "description": "",
        "image": "sanjeev-gh.jpg",
        "photoUrl": "sanjeev-gh.jpg",
        "linkedin": "https://linkedin.com/in/sanjeevgh",
        "github": ""
    },
    {
        "id": 28,
        "name": "Santhosh Kumar S",
        "registerNo": "24VL037",
        "rollno": "24VL037",
        "universityNo": "714024169037",
        "programme": "B.E. VLSI Design and Technology",
        "year": "III Year",
        "batch": "2024 - 2028",
        "email": "santosh2005th@gmail.com",
        "achievementTitle": "Hackathons, Internships & Certifications",
        "achievement": "2nd Place – Cognicode Hackathon. Participant – NeuraNexus 2K25. Internships: Manfree, Chip Crafts, Career Ladder. Certification: Java.",
        "projectsOverview": "EventLens AI, SGPA / CGPA Calculator Web App, Health Buddy – AI-Driven Public Health Chatbot",
        "description": "",
        "image": "santhosh-kumar-s.jpg",
        "photoUrl": "santhosh-kumar-s.jpg",
        "linkedin": "https://www.linkedin.com/in/santhosh-kumar-a76796304",
        "github": ""
    }
]

with open("js/api.js", "r", encoding="utf-8") as f:
    content = f.read()

target = '                github: "https://github.com/elephantgokul"\n            }\n        ]\n    };\n}'

students_str = ",\n".join(["            " + json.dumps(s, indent=4).replace("\n", "\n            ") for s in students])

replacement = f"""                github: "https://github.com/elephantgokul"
            }},
{students_str}
        ]
    }};
}}"""

if target in content:
    with open("js/api.js", "w", encoding="utf-8") as f:
        f.write(content.replace(target, replacement))
    print("Successfully updated js/api.js")
else:
    print("Could not find target string in js/api.js")
